### PR TITLE
feat(locales): add new supported locales

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes https://github.com/mozilla/fxa-shared/issues/7

@jrgm r?

### CODE REVIEW

**Comment by vladikoff** [comment]
Fixes https://github.com/mozilla/fxa-shared/issues/7

> There are new locales with 100% translation at https://pontoon.mozilla.org/projects/firefox-accounts/

**Comment by vbudhram** [comment]
@vladikoff took a look at link and some of the locales are not listed at 100%. Do all translations have to be 100% before adding?

ast - 96%
bn-BD - 94%
ka - 89%
lv - 92%
nn-no - 94%
ro - 94%

**Comment by vladikoff** [comment]
> @vladikoff took a look at link and some of the locales are not listed at 100%. Do all translations have to be 100% before adding?

I look at 'update date' and for 80%+ translation.

**Comment by jrgm** [comment]
Assuming we're all settled with `es` vs. `es-ES`, then r+

**Comment by vladikoff** [comment]
> Assuming we're all settled with es vs. es-ES, then r+

What was the concern before? (currently seems like those locales are being updated at the same time)

**Pull request merged**
