### PR TITLE
feat(l10n): shared languages

### PR DESCRIPTION
**Pull request by vladikoff**
@vbudhram feedback?

### CODE REVIEW

**Comment by vladikoff** [comment]
The goal is to include this in : https://github.com/mozilla/fxa-content-server/blob/master/server/lib/configuration.js#L229 and https://github.com/mozilla/fxa-auth-server/blob/master/config/supportedLanguages.js and in the oauth server in future

**Comment by vladikoff** [comment]
cc @pdehaan

**Comment by vbudhram** [comment]
@vladikoff I like it! I think this is a pretty straightforward way to share config and data across services. What are your thoughts on having a function that returns supported locale instead of returning json directly? I could see that being useful if we need to filter locales or manipulate list before sending back.

Looking back at the name, wonder if `fxa-utils` still makes sense? Seems like this could be used to share common components, configurations, etc.

**Comment by vladikoff** [comment]
> What are your thoughts on having a function that returns supported locale instead of returning json directly? I could see that being useful if we need to filter locales or manipulate list before sending back.

That might be useful, I'm working on the timeago feature that might benefit from that.

> Looking back at the name, wonder if fxa-utils still makes sense? Seems like this could be used to share common components, configurations, etc.

yea true, renamed to `fxa-shared`

**Pull request merged**
